name: Build Terraform Deployment Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - main

env:
  CI_DOCKER_USERNAME: ${{ secrets.CI_DOCKER_USERNAME }}
  CI_DOCKER_PASSWORD: ${{ secrets.CI_DOCKER_PASSWORD }}
  TERRAFORM_VERSION: 1.3.9

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.CI_DOCKER_USERNAME }}
          password: ${{ env.CI_DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ env.CI_DOCKER_USERNAME }}/terraform-deployment:latest, ${{ env.CI_DOCKER_USERNAME }}/terraform-deployment:${{ steps.extract_branch.outputs.branch }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            --build-arg TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
            --build-arg TARGETARCH=${{ matrix.arch }}
